# @package _global_

wandb:
  mode: offline
slurm:
  cluster: local
  num_parallel: 8
  update_parameters: # for executor.update_parameters()
    timeout_min: 10080
    slurm_partition: dev
    gpus_per_node: 1
